name = "bangumi-tv-read"
main = "src/index.ts"
compatibility_date = "2026-06-17"

[[kv_namespaces]]
binding = "BANGUMI_KV"
id = "bangumi-tv-kv"

[[r2_buckets]]
binding = "BANGUMI_R2"
bucket_name = "bangumi-tv-images"
