name = "bangumi-tv-media"
main = "src/index.ts"
compatibility_date = "2026-06-17"

[[kv_namespaces]]
binding = "BANGUMI_KV"
id = "bangumi-tv-kv"

[[r2_buckets]]
binding = "BANGUMI_R2"
bucket_name = "bangumi-tv-images"

[[queues.consumers]]
queue = "bangumi-tv-media"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
