name = "bangumi-tv-sync"
main = "src/index.ts"
compatibility_date = "2026-06-17"

[vars]
SYNC_MODE = "merge"

[triggers]
crons = ["0 */4 * * *"]

[[kv_namespaces]]
binding = "BANGUMI_KV"
id = "bangumi-tv-kv"

[[queues.producers]]
binding = "MEDIA_QUEUE"
queue = "bangumi-tv-media"
